<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="TheUsualJoints.Default" %>

<%@ Register src="footer.ascx" tagname="footer" tagprefix="uc1" %>

<!doctype html>
<!-- Microdata markup added by Google Structured Data Markup Helper. -->
<html itemscope itemtype="http://schema.org/WebPage" lang="en">
<head runat="server">
    <title>The Usual Joints - What To Do Tonight!</title>
    <meta charset="utf-8" />
    <meta name="description" content="We are your guide to what to do in Ocean City, Salisbury and Rehoboth Beach! Dining to dancing: Find out at The Usual Joints!" />
    <!-- Google Authorship and Publisher Markup goes here -->
    <link rel="author" href="https://plus.google.com/112206483966107114603" />
    <meta name="google-site-verification" content="ANEJcWIEYrEBFb7Xm46D0tQlvgC4HQ6G-dhGQsRL7w0" />
    <link rel="publisher" href="https://plus.google.com/112206483966107114603" />
    <!-- Schema.org markup for Google+ goes here -->
    <meta itemprop="name" content="The Usual Joints - What To Do Tonight!" />
    <meta itemprop="description" content="We are your guide to what to do in Ocean City, Salisbury and Rehoboth Beach! Dining to dancing: Find out at The Usual Joints!" />
    <meta itemprop="image" content="http://localhost:33428/images/cities/tuj-google-profile-250.png" />
    <!-- Twitter Card data goes here -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@theusualjoints" />
    <meta name="twitter:title" content="The Usual Joints - What To Do Tonight!" />
    <meta name="twitter:description" content="We are your guide to what to do in Ocean City, Salisbury and Rehoboth Beach! Dining to dancing: Find out at The Usual Joints!" />
    <!-- Twitter summary card with large image must be at least 280x150px -->
    <meta name="twitter:image:src" content="http://localhost:33428/images/cities/tuj-twitter-profile-400.png" />
    <!-- Open Graph data goes here -->
    <meta property="og:title" content="The Usual Joints - What To Do Tonight!" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.theusualjoints.com/" />
    <meta property="og:image" content="http://localhost:33428/images/cities/tuj-og-image-400.png" />
    <meta property="og:description" content="We are your guide to what to do in Ocean City, Salisbury and Rehoboth Beach! Dining to dancing: Find out at The Usual Joints!" />
    <meta property="og:site_name" content="The Usual Joints - What To Do Tonight!" />
    <meta property="fb:admins" content="1289024829" />
    <!-- Additional data -->
    <meta name="keywords" content="what to do, restaurants, Ocean City, Salisbury, Rehoboth Beach" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
    <meta name="robots" content="noodp" />
    <!--Remove this to test on localhost-->

    <!---->
    <link rel='icon' href='<%# Page.ResolveUrl("favicon.ico") %>' type='image/x-icon' />
    <link rel='shortcut icon' href='<%# Page.ResolveUrl("favicon.ico") %>' type='image/x-icon' />
    <script>document.createElement('main');</script>
    <!--<noscript>Your browser does not support JavaScript</noscript>-->
    <!--[if lt IE 9]>
        <script src='<%# Page.ResolveUrl("scripts/html5shiv.js") %>'></script>
    <![endif]-->
    <!-- Google Analytics script goes here -->
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-23362016-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper goes here -->
    <script type="application/ld+json"> { "@context" : "http://schema.org", "@type" : "LocalBusiness", "name" : "The Usual Joints - What To Do Tonight!", "url" : "http://www.theusualjoints.com/", "email" : "info@theusualjoints.com" } </script>
</head>
<body>
    <form id="form1" runat="server">
        <div class="default_status_bar"><asp:PlaceHolder ID="status_bar_PlaceHolder1" runat="server"></asp:PlaceHolder></div>
        <div itemscope itemtype="http://schema.org/LocalBusiness" id="default_layout" class="default_layout" runat="server">
            <br />
            <div class="default_drop_div">
                <header role="banner" class="default_text_div">
                    <asp:Image ID="default_Image1" CssClass="default_Image1" runat="server" ImageUrl="~/images/clear-default-header-logo.png" AlternateText="Welcome to The Usual Joints!" Visible="false" />
                    <h1 itemprop="name">Welcome to The Usual Joints!</h1>
                </header>
                <div role="main">
                    <div class="default_text_div">
                        <span>Looking for what to do tonight? Trying to find local bars, restaurants or clubs? Or looking for bands or DJs that play your favorite music?</span>
                        <p>Don't miss the party! Tonight, let us be your guide to the local nightlife! Our listings of bars and restaurants in Ocean City, Salisbury and Rehoboth Beach, their food and drink specials, and who's playing tonight, will get you and your friends eating, drinking and dancing quickly on your night out on the town!</p>
                        <p>Start by making a selection below:</p>
                    </div>
                    <br />
                    <nav class="default_contact_nav" role="navigation">
                        <div class="default_contact_link_div">
                            <a href="salisbury-md-c1" title="Salisbury, Delmar, Fruitland and more!"><img src="images/clear-salisbury-md-us-300.png" class="default_contact_link_img" alt="Salisbury, Delmar, Fruitland and more!" /></a> <!-- Make sure </a> touches <img> or a little blue line will show up! -->
                        </div>
                        <div class="default_contact_link_div">
                            <a href="ocean-city-md-c2" title="Ocean City, Berlin and more!"><img src="images/clear-ocean-city-md-us-300.png" class="default_contact_link_img" alt="Ocean City, Berlin and more!" /></a>
                        </div>
                        <div class="default_contact_link_div">
                            <a href="rehoboth-beach-de-c3" title="Rehoboth Beach, Dewey Beach, Lewes and more!"><img src="images/clear-rehoboth-beach-de-us-300.png" class="default_contact_link_img" alt="Rehoboth Beach, Dewey Beach, Lewes and more!" /></a>
                        </div>
                    </nav>
                    <br />
                </div>
                <footer role="contentinfo">
                    <hr />
                    <uc1:footer ID="footer1" runat="server" />
                </footer>
            </div>
        </div>
        <br />
    </form>
</body>
</html>